import { AnchorHeading } from "@/components/AnchorHeading";
import { Label } from "@/components/Label";
import { config } from "../course.config";

const base = `/c/${config.slug}`;

export function ProjectsIndexPage() {
  return (
    <>
      <AnchorHeading as="h1" id="projects">Projects</AnchorHeading>
      <p>
        Five projects span the quarter. Each builds on the last, culminating in
        an open-ended Artifact you can showcase.
      </p>

      <ul>
        <li><a href={`${base}/project/maze-game`}>Project 1 — MazeGame</a> <Label variant="purple">due Apr 7</Label></li>
        <li><a href={`${base}/project/modeler`}>Project 2 — Modeler</a> <Label variant="purple">due Apr 21</Label></li>
        <li><a href={`${base}/project/tracer`}>Project 3 — Tracer</a> <Label variant="purple">due May 5</Label></li>
        <li><a href={`${base}/project/simulator`}>Project 4 — Simulator</a> <Label variant="purple">due May 19</Label></li>
        <li><a href={`${base}/project/artifact`}>Project 5 — Artifact</a> <Label variant="red">due Jun 9</Label></li>
      </ul>
    </>
  );
}

function projectStub(title: string, blurb: string) {
  function StubPage() {
    return (
      <>
        <AnchorHeading as="h1" id="project">{title}</AnchorHeading>
        <p>{blurb}</p>
        <blockquote>
          This page is a placeholder generated by the coursemaker template.
          Replace it with the real project handout when the course is taught.
        </blockquote>
      </>
    );
  }
  return StubPage;
}

export const MazeGamePage = projectStub(
  "Project 1 — MazeGame",
  "Build a small interactive maze using affine transformations and hierarchical modeling."
);
export const ModelerPage = projectStub(
  "Project 2 — Modeler",
  "Construct a hierarchical 3D character modeler with parameter sliders."
);
export const TracerPage = projectStub(
  "Project 3 — Tracer",
  "Write a recursive ray tracer with shadows, reflection, and refraction."
);
export const SimulatorPage = projectStub(
  "Project 4 — Simulator",
  "Simulate a particle system with collisions and forces."
);
export const ArtifactPage = projectStub(
  "Project 5 — Artifact",
  "An open-ended capstone you pitch, build, and demo at the end of the quarter."
);
